baseURL: "http://127.0.0.1:2323"
# canonifyURLs: true
languageCode: "zh-cn"
title: "ecCodes教程中文版"
theme: "hugo-theme-learn"
params:
  ordersectionsby: weight

# outputs:
#   home: [ "HTML", "RSS", "JSON"]